import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          header
        </nav>
      </header>

      <div className={styles.container}>
        <aside className={styles.sidebar}>sidebar</aside>
        <div className={styles.content}>tes</div>
        <article className={styles.article}>article</article>
      </div>
      <footer className={styles.footer}>footer</footer>
    </div>
  )
}